### PR TITLE
Use mock from unittest on Python 3

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Review by thet — APPROVED** [review]
LGTM :+1: 
only some minor code formatting issues. Sometimes you don't have any blank lines between the import, sometimes 1, sometimes 2.
Probably you cannot automatically fix it without having a huge commit with a lot of formatting issues fixed.
I'd agree to fix that sometime in the future with an automatic code formatting tool when no other PRs are open.

**Comment by ale-rt** [comment]
I ran isort and removed all the fixes outside the one that are directly connected to the PR: there are too many open PR and I do not want to create unnecessary conflicts

**Pull request merged**
