### PR TITLE
Threadsafe recursion detection backport

### PR DESCRIPTION
**Pull request by pbauer**
Same as https://github.com/plone/plone.dexterity/pull/119 but for 2.6.x (Plone 5.1.x)

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
This is currently on hold because of a possible issue discussed in https://github.com/plone/plone.dexterity/pull/119

**Comment by jensens** [comment]
it is unrelated

**Comment by tisto** [comment]
@pbauer Jens fixed the issue for us, so I guess we can go ahead with the backporting. I am happy to make a release if this PR is merged.

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
FYI: The test-failures for 5.2 are irrelevant since this is for 5.1 only.

**Pull request merged**
