### PR TITLE
#187 backport to 2.x

### PR DESCRIPTION
**Pull request by mamico**
As also reported in https://github.com/plone/Products.CMFPlone/issues/3829#issuecomment-1733142496 it might be useful to have fix #187 also for 2.x versions for Plone 5.2 users

### CODE REVIEW

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
There are lots of test failures on Python 3.  Those should be fixed together with https://github.com/plone/plone.supermodel/pull/55.

I am testing these two PRs together on Jenkins now.

**Comment by mauritsvanrees** [comment]
If Jenkins is green, then an open question is whether we dare to still put those two in a Plone 5.2 release, or if we keep this in a not-yet-existing list of package versions that you can switch to if you know what you are doing.
Note that 5.2 is officially out of maintenance support.

**Comment by mamico** [comment]
> There are lots of test failures on Python 3.

That was the reason I changed this PR to draft. Thank you for carrying on.

**Review by gforcada — APPROVED** [review]

**Comment by gforcada** [comment]
IMHO we could cut new individual distribution releases but not compile a new Plone 5.2.x release, just as @mauritsvanrees suggests: if you know what you are doing, the release is there for you to easily use it, otherwise, please move to 6.x where the fix is also applied 😄

**Comment by mauritsvanrees** [comment]
Okay, I have changed the coredev 5.2 `sources.cfg` to use new branches: plone.dexterity 2.10.x and plone.supermodel 1.6.x.
Now I will merge the two PRs and they won't end up officially in 5.2.

**Comment by mauritsvanrees** [comment]
I have made releases:

```
plone.supermodel = 1.7.0
plone.dexterity = 2.11.0
```

**Comment by mauritsvanrees** [comment]
I propose to add a `newer-versions.cfg` in coredev 5.2, that includes these versions.
See https://github.com/plone/buildout.coredev/pull/899.

**Pull request merged**
