### PR TITLE
Restore webdav support when the webdav library is importable

### LINKED ISSUE #141: Restore webdav support
There is some code that is disabled if ZServer is missing.
Actually that code should depend on the presence webdav module that since Plone 5.2.2 is back.

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #141

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Review by pysailor — APPROVED** [review]
LGTM

**Pull request merged**
