### PR TITLE
Check add_permission before checking type constrains

### PR DESCRIPTION
**Pull request by jaroel**

### CODE REVIEW

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/174/
http://jenkins.plone.org/job/pull-request-4.3/61/

**Comment by jaroel** [comment]
http://jenkins.plone.org/job/pull-request-5.0/175/
http://jenkins.plone.org/job/pull-request-4.3/62/

**Comment by jaroel** [comment]
Both pass

**Comment by jaroel** [comment]
Closes #37

**Pull request merged**
