### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by serge73**
Russian translate added

### CODE REVIEW

**Comment by thet** [comment]
Thanks for the translation!
But in order to be able to merge it, you need to sign the Plone Core Contributor's Agreement. It's a legally necessary step and protects the Plone Foundation. You can find it here: http://docs.plone.org/develop/coredev/docs/agreement.html

**Comment by thet** [comment]
Oh, yes, and an entry in CHANGES.rst.

**Comment by serge73** [comment]
I send Agreement via email. Waiting...

**Comment by gforcada** [comment]
@thet @polyester contributing translations is also covered or can they go without of a Contributor's Agreement?

**Comment by polyester** [comment]
@serge73 did you email to agreements@plone.org? Because I haven't seen any coming in for now.

@gforcada the prevailing opinion is that translating po files can be done without a Contributor Agreement, since it is a 'technical translation' and not a 'creative work'. *(However, of course if you ask 3 lawyers you will get 7 opinions.)* 

So signing one is the proper way, plus it is always nice to welcome a new contributor with all the regards!

**Comment by serge73** [comment]
image

**Comment by ableeb** [comment]
@serge73 please email your signed Contributor Agreement to agreements@plone.org. It looks like you might have originally sent it to assignments@plone.org

**Comment by serge73** [comment]
1.I see the assignments@plone.orgl in the Documentation and in the Agreement (pdf). Need to fix.
2. No problems. I sent to  agreements@plone.org
"Your message was successfully delivered to the destination(s) listed below. If the message was delivered to mailbox you will receive no further notifications. Otherwise you may still receive notifications of mail delivery errors from other systems.
                   The mail system
<agreements@plone.org>: delivery via aspmx.l.google.com[173.194.71.26]:25: 250
    2.0.0 OK 1453792995 o195si26115lfa.2 - gsmtp"

**Comment by polyester** [comment]
thanks, @serge73 . I'll look into the places where assignments is still mentioned, and fix them. Your Contributor Agreement has arrived, welcome to the Plone developer community!

**Comment by serge73** [comment]
Thanks!

**Comment by gforcada** [comment]
And translations merged!

Welcome @serge73!

**Pull request merged**
