### PR TITLE
Fix recursion in FTI lookup

### PR DESCRIPTION
**Pull request by petschki**
inspired by #108 this fixes the lineage recursion error mentioned here https://github.com/collective/collective.lineage/issues/62 when looking up IDexterityFTI for the new DX-Plone-Siteroot ... though this needs some more investigation, why the FTI lookup doesn't work.

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Test are failing in a very horrible way :)

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@ale-rt after checking a bit earlier for recursion in thread, the tests are failing randomly instead of horrible ... but this works also on my productive lineage/plone6 project ... do you see anything else I could do here?

/cc @jensens

**Comment by petschki** [comment]
@ale-rt @jensens ready for merge!

**Comment by ale-rt** [comment]
Sorry I did not yet have time to check this one :/ I hope I can check that soonish

**Comment by ale-rt** [comment]
In the meanwhile if @jensens gives a green light I am totally fine merging this one

**Pull request merged**
