### PR TITLE
Modernize, remove outdated code, add code-analysis checks

### PR DESCRIPTION
**Pull request by mauritsvanrees**
@jensens I saw your closed PR #160 again after I started this. I took over a few ideas, but probably not all. Some room for improvement in a later PR, or if you want you can edit this one.

@ericof I added the `plone/code-analysis` action/docker here, in a bit trimmed down form. I only have `make format` and `make lint`, and only one GitHub action job which runs all checks after each other.

### CODE REVIEW

**Comment by wesleybl** [comment]
I still don't understand the advantage of running code-analysis in a container. It's faster? On the first run it sure takes longer. Wouldn't creating a venv solve the problem?

**Review by jensens — APPROVED** [review]

**Review by ericof — APPROVED** [review]
LGTM

**Comment by ericof** [comment]
> I still don't understand the advantage of running code-analysis in a container. It's faster? On the first run it sure takes longer. Wouldn't creating a venv solve the problem?

The idea of having a GitHub action that does that was to have sane defaults and versions for all tools, something that is reproducible easily.

Having the action to use a pre-built Docker image speeds up everything, reducing the time to a few seconds.

Now, locally, we decided to go with the Docker image to avoid unpleasant surprises when it comes to versions (and yes, that happened a lot).

**Comment by mauritsvanrees** [comment]
> I still don't understand the advantage of running code-analysis in a container. It's faster? On the first run it sure takes longer. Wouldn't creating a venv solve the problem?

On my laptop `make format` in this repo takes 3.6 seconds, `make lint` takes 7.6 seconds. That is fast enough. Certainly much faster than I had expected with my very limited Docker experience.

A venv works too. You could add a `tox.ini` that installs all these tools, either in one shared or in multiple venvs, and call for example `tox -e format` and `tox -e lint`. But then you have to store a list of versions somewhere, either in `tox.ini` or a constraints file. And each repository will have its own list of versions. And each its own Python version to run them with. And you have one or more venvs in every repository. And then you have a passing lint check locally, and in gh-actions it fails and you have to figure out why.

In contrast, with the Docker approach, you download the image once, and then use it in all repositories. There is one version number (1.0.1)  for the used image in `Makefile`.

There are multiple ways to tackle this, with pros and cons, and I don't think we have the best solution yet. I still feel like I am exploring possibilities. Some of my goals:

- Run the same checks, with the same versions and config locally and on gh-actions.
- Do this in as few lines of code as possible. I don't like Makefiles or gh-actions yaml files with hundreds of lines. They tend to gather cruft that no one dares clean up because someone might be using it.

**Pull request merged**
