### PR TITLE
Robustify type checking in regards to py2/py3 for WebDAV

### PR DESCRIPTION
**Pull request by Rotonen**
Spotted from https://github.com/plone/plone.dexterity/pull/102
Closes https://github.com/plone/plone.dexterity/issues/103

### CODE REVIEW

**Comment by Rotonen** [comment]
@jenkins-plone-org please run jobs

**Comment by datakurre** [comment]
Thanks for catching this.

**Comment by Rotonen** [comment]
Now built together with: https://github.com/plone/plone.rfc822/pull/8

**Comment by Rotonen** [comment]
So the check here is unnecessary and the decode is the wrong thing to do:
https://github.com/plone/plone.dexterity/blob/69653a66a172436cab76b8871f8555172875f582/plone/dexterity/filerepresentation.py#L839-L840

And it was put into place as `plone.rfc822` had an unported typecheck for checking if the payload is a single payload or a multipart payload:
https://github.com/plone/plone.rfc822/blob/528ceafd750aa13848a9020ab8a7debf1070c283/plone/rfc822/_utils.py#L248-L249

**Pull request merged**
