### PR TITLE
check allowed types for add form

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
and here is the PR tests: http://jenkins.plone.org/job/pull-request-5.0/37/

**Comment by frapell** [comment]
@vangheem where there tests already for this?

**Comment by vangheem** [comment]
I didn't write any new tests. Just saying, once the test suite clears.

**Comment by frapell** [comment]
@vangheem I see... now, I was thinking, shouldn't this happen in some more lower level place? like ```addContentToContainer``` or something? I mean... is this restriction something for the UI? should content be allowed to be added programatically even if it is restricted?

I think this was the case for AT as well, right? you couldn't add it with invokeFactory if it was disallowed, right?

**Comment by vangheem** [comment]
That is correct with AT but it was annoying when you wanted to
programmatically override it(had to use more arcane constructors) . IMO, it
should only be enforced on the UI. This would be an improvement over AT.

**Comment by frapell** [comment]
@vangheem tests failed

**Comment by vangheem** [comment]
Just one. Should be an easy fix.

@vangheem <https://github.com/vangheem> tests failed

—
Reply to this email directly or view it on GitHub
<https://github.com/plone/plone.dexterity/pull/31#issuecomment-115482317>.

**Comment by vangheem** [comment]
Fixed with: https://github.com/plone/plone.dexterity/commit/7966d95137ae2cfc25decefc1ad38b1ec0d6173b

ready to merge.

**Comment by frapell** [comment]
@vangheem can you give me permission so I can rebuild the test? or maybe restart it yourself?

**Comment by vangheem** [comment]
I just merged. Just one failed test that I reproduced and fixed locally.

**Comment by frapell** [comment]
@vangheem cool, thanks

**Comment by vangheem** [comment]
@tisto @gforcada @bloodbare how do we hand out access on jenkins?

**Comment by gforcada** [comment]
@vangheem anyone with a github account can trigger jobs on jenkins... @frapell which button where you missing?

**Comment by frapell** [comment]
@gforcada I just went to the url @vangheem posted ( http://jenkins.plone.org/job/pull-request-5.0/37/ ) and clicked the "Build Now" button (which, I guess will update the code and run the tests again). After doing so, I got "An error occured. Please try again." error message on top

**Comment by gforcada** [comment]
@frapell ignore that button sorry, we need to fix that, at least for the pull request ones...

You need to go to the pull request job: http://jenkins.plone.org/job/pull-request-5.0 and then on the left column you have a "build with parameters" (provided you first have logged-in).

**Comment by frapell** [comment]
@gforcada ah ! got it, thanks!

**Pull request merged**
