### PR TITLE
Fix WebDAV traversal

### LINKED ISSUE #195: Problem with webdav and Plone 6 when the site is published using virtual hosting
Since Plone 6, the Plone site is a dexterity object.
The dexterity objects have a custom traverser that contains webdav related customizations:

https://github.com/plone/plone.dexterity/blob/9d79be15c0599c77e0f00473519d0d4feae6c87a/plone/dexterity/browser/traversal.py#L45-L56

This customizations fail to handle properly the traversal when virtual hosting is used.

The path that has to be traversed looks like:
```
/VirtualHostBase/https/example.org/Plone/VirtualHostRoot/foo/bar
```

The part before the `VirtualHostRoot` is resolved fine, but when the traverser tries to access the `VirtualHostRoot` it returns a `NullResource`.

The errors you will see is:
```
2024-02-22 10:53:54,058 ERROR   [Zope.SiteErrorLog:35][waitress-0] Conflict: https://example.com/Plone/virtual_hosting/
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 391, in publish_module
  Module ZPublisher.WSGIPublisher, line 269, in publish
  Module ZPublisher.BaseRequest, line 515, in traverse
  Module ZPublisher.BaseRequest, line 348, in traverseName
  Module ZPublisher.BaseRequest, line 82, in publishTraverse
  Module webdav.NullResource, line 86, in __bobo_traverse__
webdav.common.Conflict: Collection ancestors must already exist.
```

The site will return an error 409:

```log
[22/Feb/2024:10:14:03 +0200] "LOCK /VirtualHostBase/https/example.com%3A443/Plone/VirtualHostRoot/foo/bar.docx HTTP/1.1" 409 26 "-" "Zope External Editor/1.2.0.dev0"
```

### PR DESCRIPTION
**Pull request by ale-rt**
Fix a traversal error that happens when traversing a WebDAV resource and the virtual host monster is used.

Fixes #195

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM, seems to work.

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
