### PR TITLE
Avoid duplicate fields within DX Add/Edit/View forms

### PR DESCRIPTION
**Pull request by avoinea**
See #144

### CODE REVIEW

**Comment by avoinea** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
Beautiful +51 failing tests.

 Actually I was expecting it :smile:

**Comment by avoinea** [comment]
@ale-rt @jensens I'm not sure how should I continue with this as it seems we have chicken and egg problem here.

See also https://github.com/plone/plone.app.event/pull/325

**Comment by gforcada** [comment]
As for testing, you can test multiple pull requests at the same time with the pull requests jobs :+1: you have to start them manually though

**Comment by mauritsvanrees** [comment]
Closing, see https://github.com/plone/plone.dexterity/issues/144#issuecomment-1444632183.

**Pull request closed without merging**
