### PR TITLE
DefaultReadFile properly implements the IStreamIterator interface

### LINKED ISSUE #138: IStreamIterator interface is not respected
This test fails:
```
    def test_defaultreadfile_verify_iface(self):
        from plone.dexterity.filerepresentation import DefaultReadFile
        from zope.interface.verify import verifyObject
        from ZPublisher.Iterators import IStreamIterator

        dummy = DefaultReadFile(ItemDummy())
        self.assertTrue(IStreamIterator.providedBy(dummy))
        self.assertTrue(verifyObject(IStreamIterator, dummy))
```
with:
```
zope.interface.exceptions.MultipleInvalid: The object <plone.dexterity.filerepresentation.DefaultReadFile object at 0x7f329a50b910> has failed to implement interface <InterfaceClass ZPublisher.Iterators.IStreamIterator>:
    The ZPublisher.Iterators.IUnboundStreamIterator.__next__() attribute was not provided
    The ZPublisher.Iterators.IStreamIterator.__len__() attribute was not provided
```

That prevents to iterate on a `DefaultReadFile` instance, which instead is expected.

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #138

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
This has been split in two commits:
1) https://github.com/plone/plone.dexterity/pull/139/commits/a48414d27b9d34ee8ea66da62b83d8058dc7973f to fix the usage of the mock library
2) To actually fix #138

**Comment by ale-rt** [comment]
There is one test failing with Py 3.6 and Py 3.7 (probably due to mock internals), I am trying to see if I am more lucky with #140.
If #140 this PR should be rebased on master dropping a48414d

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Review by pysailor — APPROVED** [review]
Looks good to me. It provides the 2 missing elements `__len__` and `__next__` that the error in #138 is complaining about.

**Pull request merged**
